[package]
name = "lru"
version = "0.1.0"
authors = ["Newton Ni <nwtnni@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.4"
dirs = "2.0.2"
fxhash = "0.2.1"
indexmap = "1.3.2"
